### ISSUE TITLE
Keep attributes after conservative regridding

### ISSUE THREAD

**Issue by kjdoore** [EXCITED-CO2/xarray-regrid#26]
When regridding a data set using the `conservative` method, all attributes from the original `xarray` object are lost. It would be nice if those attributes could remain attached to the regridded data set like the `linear` method.

**Comment by BSchilperoort** [comment]
Hi Keith, thanks for opening this issue! I hope that the package has been useful for you. I have added tests for this, and fixed the issue in #27.

Would you be willing/able to review the PR? Then I'll mark you as reviewer. If you're unsure about this that OK.

**Comment by kjdoore** [comment]
Hi Bart, thanks for updating this so quickly! I would be happy to review the PR for you.

I have a project that I am working on that currently uses `xESMF`, but I am trying to switch away from it due to its large dependencies and the preference of using `xarray` add-ons vs specific packages. I have another issue related to the handling of `NaN`s that I have noticed, which I will bring up as new issues.

**Comment by BSchilperoort** [comment]
I have added you as a collaborator, if you could leave a review that'd be great.

The heaviness of xESMF and other packages is exactly why I started this package. And of course ESMF is not available on e.g. Windows which was a downside we encountered in other projects.

Any other issues would be very welcome, that'd really help with improving this package.
