### ISSUE TITLE
Questions: Python >=3.10 dependency

### ISSUE THREAD

**Issue by kobebryant432** [EXCITED-CO2/xarray-regrid#37]
Is it possible to include python 3.9 or is there a specific reason why it is excluded?

I was also wondering if it is the ambition for this to become part of xarray eventually?

**Comment by BSchilperoort** [comment]
Hi Kobe, thanks for your questions.

It might be possible that the package could work on python 3.9 with some minor changes, but as numpy and xarray stopped supporting 3.9 for new versions I would prefer to not put time into that now (more info [here](https://numpy.org/neps/nep-0029-deprecation_policy.html), xarray follows this system as well).

I would be open to (parts) of this package being merged into xarray itself, however there are a lot of geo-data specific things happening here (for example weighing data by latitude in the conservative regridder). 
Additionally, the linear/nearest-neighbor/cubic methods are mostly a wrapper around xarray's `interp` method. This package makes those easier to use in a regridding context.

Moving this repository to https://github.com/xarray-contrib could be nice though.

**Comment by kobebryant432** [comment]
Thanks for the quick response Bart. 
Understandable that you prefer not to do additional work for older versions - guess it may be time for me to start using python 3.10.

Indeed  https://github.com/xarray-contrib looks like a good place for this!

In any case I think this lightweight regridding in python is very usefull. I will try to use it in my current project and might (no promises) have some time to contribute here.

**Comment by jhamman** [comment]
> Is it possible to include python 3.9 or is there a specific reason why it is excluded?

Noting that Xarray is currently dropping support for python 3.9: https://github.com/pydata/xarray/pull/8937

> Moving this repository to https://github.com/xarray-contrib could be nice though.

Xarray dev here. Happy to help make this happen if you are up for it. Guidelines are [here](https://github.com/xarray-contrib/xarray-contrib?tab=readme-ov-file#guidelines) when you want to move forward on this.

**Comment by BSchilperoort** [comment]
Move to xarray-contrib has been initiated!
